package cn.beecloud;

public class BCEumeration {
	
	public enum RESULT_TYPE {
		OK,
        APP_INVALID,
        PAY_FACTOR_NOT_SET,
        CHANNEL_INVALID,
        MISS_PARAM,
        PARAM_INVALID,
        CERT_FILE_ERROR,
        CHANNEL_ERROR,
        NO_SUCH_BILL,
        DUPLICATED_PREFUND_RECORD,
        BILL_UNSUCCESS,
        REFUND_EXCEED_TIME,
        ALREADY_REFUNDING,
        REFUND_AMOUNT_TOO_LARGE,
        NO_SUCH_REFUND,
        RECORD_DUPLICATE,
        RUNTIME_ERORR,
        NOT_CORRECT_RESPONSE,
        OTHER_ERROR
	}

	public enum PAY_CHANNEL {
		WX,
		WX_APP,
		WX_NATIVE,
		WX_JSAPI,
		ALI,
		ALI_APP,
		ALI_WEB,
		ALI_WAP,
		ALI_QRCODE,
		ALI_OFFLINE_QRCODE,
		UN,
		UN_APP,
		UN_WEB,
		YEE,
		YEE_WEB,
		YEE_WAP,
		YEE_NOBANKCARD,
		JD,
		JD_WEB,
		JD_WAP,
		KUAIQIAN,
		KUAIQIAN_WAP,
		KUAIQIAN_WEB,
		BD,
		BD_WEB,
		BD_WAP,
		PAYPAL,
		PAYPAL_SANDBOX,
		PAYPAL_LIVE
	}

	public enum QR_PAY_MODE {
		MODE_BRIEF_FRONT,
		MODE_FRONT,
		MODE_MINI_FRONT
	}
}



